/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdbool.h"
#include "string.h"
#include "stm32f411xx.h"
#include "gpio_driver.h"
#include "spi_driver.h"
#include "test.h"

/* Init MACROs */
#define LED_INIT		0
#define SWITCH_INIT		0
#define BTN_INIT		0
#define SPI_INIT		1

#define LED_TEST 		0
#define SWITCH_TEST 	0
#define BTN_INT_TEST 	0 //!SWITCH_TEST
#define SPI_TEST		1

#define SAMPLE_IRQ		0

#if BTN_INT_TEST
#define GPIO_IT_PORT	GPIOC
#define GPIO_IT_PIN		GPIO_PIN_13
volatile _Bool USER_KEY = true;
#endif


void sw_delay(void)
{
	for(uint32_t i=0;i<5000;i++);
}

#if SAMPLE_IRQ
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandler(GPIO_PIN_13);  //clear PR
	GPIO_PinToggle(GPIOA, GPIO_PIN_5); //toggle led
}
#endif

#if BTN_INT_TEST
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandler(GPIO_PIN_13);  //clear PR
	USER_KEY = false;
}
#endif


void SPI2GPIO_Init()
{
	GPIO_Handle_t SPI2_gpio;
	memset(&SPI2_gpio,0,sizeof(SPI2_gpio));

	SPI2_gpio.pGPIO = GPIOB;
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_ALTFN;
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_PUSHPULL;

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOB,ENABLE);
	//Slave Select Pin
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_12;
	/* Init GPIO */
	GPIO_Init(&SPI2_gpio);

	//Sclk Pin
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	/* Init GPIO */
	GPIO_Init(&SPI2_gpio);
	//MISO
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_14;
	/* Init GPIO */
	GPIO_Init(&SPI2_gpio);
	//MOSI
	SPI2_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_15;
	/* Init GPIO */
	GPIO_Init(&SPI2_gpio);

}

void SPI2_Init()
{
	SPI_Handle_t peri_spi2;
	memset(&peri_spi2,0,sizeof(peri_spi2));

	//SPI 2 as master
	peri_spi2.pSPI_PinConfig.SPI_BusConfig = SPI_BCFG_FD;
	peri_spi2.pSPI_PinConfig.SPI_DeviceMode = SPI_DEV_MODE_MASTER;
	peri_spi2.pSPI_PinConfig.SPI_ClkSpeed = SPI_PCLK_DIV2;  //Fclk/2
	peri_spi2.pSPI_PinConfig.SPI_DFF = SPI_DFF_8BIT;
	peri_spi2.pSPI_PinConfig.SPI_SSM = SPI_SSM_ENA;
	peri_spi2.pSPI_PinConfig.SPI_CPHA = SPI_CPHA_ZERO;
	peri_spi2.pSPI_PinConfig.SPI_CPOL = SPI_CPOL_ZERO;

	//enable pclk
	SPI_Pclk_Control(SPI2,ENABLE);

	//INIT SPI
	SPI_Init(&peri_spi2);

	SPI_SSI_SET(SPI2);

	SPI_Enable(SPI2);

}

int main(void)
{
	printf("hello world\n");

	/* Declare Config Structure */
	GPIO_Handle_t led_gpio,gpio_Pushbtn;
	memset(&led_gpio,0,sizeof(led_gpio));
	memset(&gpio_Pushbtn,0,sizeof(gpio_Pushbtn));


#if LED_INIT
	/* Initialize Config Structure for LED */
	led_gpio.pGPIO = GPIOA;
	led_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	led_gpio.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_OUT;
	led_gpio.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	//led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	//led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_PUSHPULL;
	led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
	led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;
	//NOTE: if v use led_gpio->pGPIO_PinConfig.GPIO_PinOPType with "->" invalid type argument error will come use "."

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOA,ENABLE);

	/* Init GPIO */
	GPIO_Init(&led_gpio);
#endif

#if SWITCH_INIT
	/* Initialize Config Structure for PushButon */
	gpio_Pushbtn.pGPIO = GPIOC;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_IN;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOC,ENABLE);

	/* Init GPIO */
	GPIO_Init(&gpio_Pushbtn);
#endif

#if BTN_INIT
	/* Initialize Config Structure for PushButon */
	gpio_Pushbtn.pGPIO = GPIOC;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_IT_FT;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
	//led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOC,ENABLE);

	/* Init GPIO */
	GPIO_Init(&gpio_Pushbtn);

	//IRQ Configurations
	GPIO_IRQHandler(GPIO_PIN_13); //clear pending INT
	GPIO_IRQ_Interrupt_Config(IRQ_NO_EXTI15_10,ENABLE);

#endif

/* 	SPI_Pclk_Control(SPI2,ENABLE);
	printf(" %d \n ",(SPI2->SPI_CR1) & (1<<SPI_CR1_SSI_BPOS));
	//SPI2->SPI_CR1 |=  1<<SPI_CR1_SSI_BPOS;
	SPI_SSI_SET(SPI2);
	printf(" %d \n ",(SPI2->SPI_CR1) & (1<<SPI_CR1_SSI_BPOS));

	printf(" %d \n ",(SPI2->SPI_CR1) & (1<<SPI_CR1_SPE_BPOS));
	SPI_Enable(SPI2);
	//SPI2->SPI_CR1 |=  1<<SPI_CR1_SPE_BPOS;
	printf(" %d \n ",(SPI2->SPI_CR1) & (1<<SPI_CR1_SPE_BPOS));
	while(1);
*/

#if SPI_INIT
	SPI2GPIO_Init();
	SPI2_Init();
	SPI_SSI_SET(SPI2);
	SPI_Enable(SPI2);
#endif

#if SPI_TEST
	uint8_t test_str[] = {0};
	for(int i=0;i<32;i++)
	{test_str[i]=i;}
	SPI_DataSend(SPI2,test_str,32);
	while(1);

#endif

#if 1
	/* Infinit Loop */
	while(1)
	{

#if LED_TEST
		//Test_LED();
		GPIO_PinToggle(GPIOA,GPIO_PIN_5);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
		sw_delay();

		/* LED ON */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,ENABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();

		/* LED OFF */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,DISABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
#endif

#if SWITCH_TEST
		uint8_t Pbtn = 0;
		printf(" %d \n ",GPIO_PinRead(GPIOC,GPIO_PIN_13));
		Pbtn = GPIO_PinRead(GPIOC,GPIO_PIN_13);
		if(Pbtn == 0)
		{
			sw_delay();
			printf("Pushbutton : ON \n");
			/* LED ON */
			GPIO_PinWrite(GPIOA,GPIO_PIN_5,ENABLE);
		}
		else
		{
			sw_delay();
			printf("Pushbutton : OFF \n");
			/* LED OFF */
			GPIO_PinWrite(GPIOA,GPIO_PIN_5,DISABLE);
		}

#endif

#if BTN_INT_TEST
		if(USER_KEY == false)
		{
			printf(" USER PUSHBUTTON PRESSED \n ");
			printf(" %d \n ",GPIO_PinRead(GPIOC,GPIO_PIN_13));
			USER_KEY = true;
			GPIO_PinToggle(GPIOA,GPIO_PIN_5);
			printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		}
#endif

	}//end of while(1)
#endif//disable While(1) infiniite loop

	return 0;
}//end of main
