/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stm32f411xx.h"
#include "gpio_driver.h"
#include "test.h"


#define LED_TEST 1

void sw_delay(void)
{
	for(uint32_t i=0;i<5000;i++);
}

int main(void)
{
	printf("hello world\n");

	/* Declare Config Structure */
	GPIO_Handle_t led_gpio;

	/* Initialize Config Structure */
	led_gpio.pGPIO = GPIOA;
	led_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	led_gpio.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_OUT;
	led_gpio.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	//led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	//led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_PUSHPULL;
	led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
	led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;
	//NOTE: if v use led_gpio->pGPIO_PinConfig.GPIO_PinOPType with "->" invalid type argument error will come use "."

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOA,ENABLE);

	/* Init GPIO */
	GPIO_Init(&led_gpio);

	/* Infinit Loop */
	while(1)
	{
		//Test_LED();
		GPIO_PinToggle(GPIOA,GPIO_PIN_5);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
#if 0
		/* LED ON */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,ENABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();

		/* LED OFF */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,DISABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
#endif

	}

	return 0;
}
