/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdbool.h"
#include "string.h"
#include "stm32f411xx.h"
#include "gpio_driver.h"
#include "test.h"


#define LED_TEST 		0
#define SWITCH_TEST 	0
#define BTN_INT_TEST 	!SWITCH_TEST
#define SAMPLE_IRQ		0

#if BTN_INT_TEST
#define GPIO_IT_PORT	GPIOC
#define GPIO_IT_PIN		GPIO_PIN_13
volatile _Bool USER_KEY = true;
#endif


void sw_delay(void)
{
	for(uint32_t i=0;i<5000;i++);
}

#if SAMPLE_IRQ
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandler(GPIO_PIN_13);  //clear PR
	GPIO_PinToggle(GPIOA, GPIO_PIN_5); //toggle led
}
#else
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandler(GPIO_PIN_13);  //clear PR
	USER_KEY = false;
}
#endif

int main(void)
{
	printf("hello world\n");

	/* Declare Config Structure */
	GPIO_Handle_t led_gpio,gpio_Pushbtn;
	memset(&led_gpio,0,sizeof(led_gpio));
	memset(&gpio_Pushbtn,0,sizeof(gpio_Pushbtn));

	/* Initialize Config Structure for LED */
	led_gpio.pGPIO = GPIOA;
	led_gpio.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	led_gpio.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_OUT;
	led_gpio.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	//led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	//led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_PUSHPULL;
	led_gpio.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
	led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;
	//NOTE: if v use led_gpio->pGPIO_PinConfig.GPIO_PinOPType with "->" invalid type argument error will come use "."

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOA,ENABLE);

	/* Init GPIO */
	GPIO_Init(&led_gpio);

#if SWITCH_TEST
	/* Initialize Config Structure for PushButon */
	gpio_Pushbtn.pGPIO = GPIOC;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_IN;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOC,ENABLE);

	/* Init GPIO */
	GPIO_Init(&gpio_Pushbtn);
#endif

#if BTN_INT_TEST
	/* Initialize Config Structure for PushButon */
	gpio_Pushbtn.pGPIO = GPIOC;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinMode = GPIO_PINMODE_IT_FT;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinSpeed = GPIO_OUTSPEED_FAST;
	gpio_Pushbtn.pGPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
	//led_gpio.pGPIO_PinConfig.GPIO_PinOPType = GPIO_OT_OPENDRAIN;

	/* Enable Peripheral Clock*/
	GPIO_Pclk_Control(GPIOC,ENABLE);

	/* Init GPIO */
	GPIO_Init(&gpio_Pushbtn);

	//IRQ Configurations
	GPIO_IRQHandler(GPIO_PIN_13); //clear pending INT
	GPIO_IRQ_Interrupt_Config(IRQ_NO_EXTI15_10,ENABLE);

#endif


	/* Infinit Loop */
	while(1)
	{

#if BTN_INT_TEST
		if(USER_KEY == false)
		{
			printf(" USER PUSHBUTTON PRESSED \n ");
			printf(" %d \n ",GPIO_PinRead(GPIOC,GPIO_PIN_13));
			USER_KEY = true;
			GPIO_PinToggle(GPIOA,GPIO_PIN_5);
			printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		}
#endif

#if SWITCH_TEST
		uint8_t Pbtn = 0;
		printf(" %d \n ",GPIO_PinRead(GPIOC,GPIO_PIN_13));
		Pbtn = GPIO_PinRead(GPIOC,GPIO_PIN_13);
		if(Pbtn == 0)
		{
			sw_delay();
			printf("Pushbutton : ON \n");
			/* LED ON */
			GPIO_PinWrite(GPIOA,GPIO_PIN_5,ENABLE);
		}
		else
		{
			sw_delay();
			printf("Pushbutton : OFF \n");
			/* LED OFF */
			GPIO_PinWrite(GPIOA,GPIO_PIN_5,DISABLE);
		}

#endif

#if LED_TEST
		//Test_LED();
		GPIO_PinToggle(GPIOA,GPIO_PIN_5);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
		sw_delay();

		/* LED ON */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,ENABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();

		/* LED OFF */
		GPIO_PinWrite(GPIOA,GPIO_PIN_5,DISABLE);
		printf(" %d \n ",GPIO_PinRead(GPIOA,GPIO_PIN_5));
		sw_delay();
#endif

	}//end of while(1)

	return 0;
}//end of main
